Fix benchmark CI by not hardcoding repo name

diff --git a/.github/workflows/run-benchmark.yml b/.github/workflows/run-benchmark.yml
--- a/.github/workflows/run-benchmark.yml
+++ b/.github/workflows/run-benchmark.yml
@@ -43,7 +43,7 @@ jobs:
         id: commit-info
         run: |
           if [[ -n '${{ inputs.sha }}' ]]; then
-            FULL_SHA="$(curl "https://api.github.com/repos/vapor/multipart-kit/commits/${{ inputs.sha }}" | jq -r '.sha')"
+            FULL_SHA="$(curl "https://api.github.com/repos/${{ github.repository }}/commits/${{ inputs.sha }}" | jq -r '.sha')"
 
             # Get the oldest PR that contains the commit
             PR="$(
@@ -53,6 +53,11 @@ jobs:
 
             PR_TITLE="$(echo "${PR}" | jq -r '.title')"
             PR_NUMBER="$(echo "${PR}" | jq -r '.number')"
+
+            if [[ -z "${PR_NUMBER}" ]]; then
+              echo 'failed to find PR info for commit '${{ inputs.sha }}''
+              exit 1
+            fi
 
             echo "ref=${FULL_SHA}" >> "${GITHUB_OUTPUT}"
             echo "sha=${FULL_SHA}" >> "${GITHUB_OUTPUT}"
